export NUPLAN_MAP_VERSION="nuplan-maps-v1.0"
export NUPLAN_MAPS_ROOT="/maps"
export NAVSIM_EXP_ROOT="/workspace/PriorEye/exp"
export NAVSIM_CACHE_ROOT="/workspace/PriorEye/cache"
export NAVSIM_DEVKIT_ROOT="/workspace/PriorEye"
export OPENSCENE_DATA_ROOT="/dataset"
export NAVSIM_TRAJPDM_ROOT="/dataset/traj_pdm_v2"
export NUPLAN_GSV_EMBEDDING_ROOT="/dataset/embedding"